services:
  postgres:
    image: postgres:16
    container_name: turnero-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: turnero
      POSTGRES_USER: turnero_user
      POSTGRES_PASSWORD: turnero_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: