spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/turnero
    username: turnero_user
    password: turnero_pass

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

clinic:
  max-concurrent-appointments: 2